### ISSUE TITLE
Trailing Slash in YAML

### ISSUE THREAD

**Issue by ibracorp** [aeleos/cloudflared#6]
On the line:
```
# forward all traffic to Reverse Proxy w/ SSL
ingress:
  - service: https://REVERSEPROXYIP:PORT/
    originRequest:
      originServerName: yourdomain.com
```
Need to remove the trailing slash at the end of ingress service like so:
```
  - service: https://REVERSEPROXYIP:PORT
```
